name: Terraform Infra (AWS Resources)

on:
  push:
    branches:
      - main

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      ecr_name: ${{ steps.get-ecr-name.outputs.ecr_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
          terraform_wrapper: true

      - name: Generate SSH Key Pair
        run: |
          ssh-keygen -t rsa -b 2048 -f ddg-dl-temp -N "" -q
          echo "Claves generadas"

      - name: Set key name in environment
        run: |
          echo "KEY_NAME=temp-key-${{ github.run_id }}" >> $GITHUB_ENV

      - name: Import Public Key to AWS
        run: |
          aws ec2 import-key-pair \
            --key-name ${{ env.KEY_NAME }} \
            --public-key-material "$(base64 -w 0 ddg-dl-temp.pub)"

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Scan
        uses: snyk/actions/iac@master
        continue-on-error: true
        with:
          file: terraform/
          json: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Terraform Plan
        id: terraform-plan
        run: |
          terraform -chdir=terraform plan -var "key_name=${{ env.KEY_NAME }}"

      - name: Terraform Apply
        id: terraform-apply
        run: terraform -chdir=terraform apply -auto-approve -var "key_name=${{ env.KEY_NAME }}"

      - name: Obtener la id del Security Group de la instancia EC2
        run: |
          cd terraform
          SECURITY_GROUP_ID=$(terraform output -raw security_group_id)
          echo "SECURITY_GROUP_ID=$SECURITY_GROUP_ID" >> $GITHUB_ENV

      - name: Get Runner IP Address
        id: runner_ip
        uses: haythem/public-ip@v1.3

      - name: Whitelist Runner IP Address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id ${{ env.SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.runner_ip.outputs.ipv4 }}/32

      - name: Obtener la dirección IP pública de EC2
        run: |
          cd terraform
          PUBLIC_IP=$(terraform output -raw public_ip)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Get ECR Name
        run: |
          cd terraform
          ECR_NAME=$(terraform output -raw repository_name)
          echo "ECR_NAME=$ECR_NAME" >> $GITHUB_ENV 

      - name: Esperar a que la instancia EC2 esté disponible
        run: |
          aws ec2 wait instance-status-ok --instance-ids ${{ env.INSTANCE_ID }}
          echo "La instancia EC2 está lista."

      - name: Instalar rsync
        run: sudo apt-get install -y rsync

      - name: Transferir archivos a EC2 excluyendo la carpeta 'public'
        run: |
          rsync -avz \
            --exclude 'public' \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude '.github' \
            --exclude '.gitignore' \
            --exclude 'terraform' \
            --exclude 'ddg-dl-temp' \
            --exclude 'ddg-dl-temp.pub' \
            -e "ssh -i ddg-dl-temp -o StrictHostKeyChecking=no" ./ ec2-user@${{ env.PUBLIC_IP }}:/home/ec2-user/app/

      - name: Desplegar aplicación en EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ddg-dl-temp ec2-user@${{ env.PUBLIC_IP }} << 'EOF'
            sudo yum update -y
            sudo yum install -y nodejs
            sudo npm install -g pm2
            cd /home/ec2-user/app
            npm install
            pm2 start index.js
            pm2 save
            pm2 startup
            echo "Aplicación desplegada"
          EOF

      - name: Verificar que la API está activa
        run: |
          curl -I http://${{ env.PUBLIC_IP }}:3000/api

      - name: Eliminar claves SSH temporales
        run: |
          rm -f ddg-dl-temp ddg-dl-temp.pub

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

      - name: Build/Tag Docker Image
        run: |
          docker build -t dl-web-app:latest .
          docker tag dl-web-app:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ env.ECR_NAME }}:latest

      - name: Run Snyk Docker Scan
        continue-on-error: true
        uses: snyk/actions/docker@master
        with:
          image: dl-web-app
          args: --file=Dockerfile --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ env.ECR_NAME }}:latest

      - name: Scan ECR Image
        continue-on-error: true
        uses: snyk/actions/docker@master
        with:
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ env.ECR_NAME }}:latest
          args: --file=Dockerfile --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      - name: Revoke Runner IP Address
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id ${{ env.SECURITY_GROUP_ID }} \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.runner_ip.outputs.ipv4 }}/32
